const categoriesData = [
  {
    name: 'Quần Áo & Thời Trang Bé',
    slug: 'quan-ao-thoi-trang-be',
    description: 'Quần áo sơ sinh, bodysuit cotton organic mềm mịn, an toàn tuyệt đối cho làn da nhạy cảm.',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&auto=format&fit=crop&q=80',
    order: 1,
  },
  {
    name: 'Đồ Chơi Thông Minh & Vận Động',
    slug: 'do-choi-thong-minh-van-dong',
    description: 'Đồ chơi phát triển trí tuệ, lego, xếp hình gỗ Montessori an toàn không độc hại.',
    icon: 'Gamepad2',
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500&auto=format&fit=crop&q=80',
    order: 2,
  },
  {
    name: 'Sữa & Thực Phẩm Ăn Dặm',
    slug: 'sua-thuc-pham-an-dam',
    description: 'Sữa công thức dinh dưỡng, bánh ăn dặm organic, bột ăn dặm nhập khẩu chính hãng.',
    icon: 'Utensils',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    order: 3,
  },
  {
    name: 'Tã Bỉm & Chăm Sóc Vệ Sinh',
    slug: 'ta-bim-cham-soc-ve-sinh',
    description: 'Tã dán, tã quần siêu thấm hút, sữa tắm gội dịu nhẹ và khăn ướt kháng khuẩn cho bé.',
    icon: 'HeartHandshake',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500&auto=format&fit=crop&q=80',
    order: 4,
  },
  {
    name: 'Xe Đẩy, Địu & Nôi Cũi Em Bé',
    slug: 'xe-day-diu-noi-cui-em-be',
    description: 'Xe đẩy gấp gọn du lịch, địu trợ lực chống gù lưng, nôi rung tự động ru bé ngủ ngon.',
    icon: 'Baby',
    image: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=500&auto=format&fit=crop&q=80',
    order: 5,
  },
];

const productsData = [
  {
    name: 'Set 3 Bộ Bodysuit Cotton Organic Sơ Sinh GrowKid Soft',
    slug: 'set-3-bo-bodysuit-cotton-organic-so-sinh-growkid-soft',
    brand: 'GrowKid Pure',
    categorySlug: 'quan-ao-thoi-trang-be',
    ageGroup: '0-12m',
    gender: 'unisex',
    description: 'Set 3 bộ áo liền thân (bodysuit) dệt từ 100% sợi cotton hữu cơ mềm mại, co giãn 4 chiều tự nhiên, thấm hút mồ hôi vượt trội. Cúc bấm đáy mạ niken chống gỉ giúp ba mẹ dễ dàng thay tã mà không làm phiền giấc ngủ của con.',
    specifications: {
      material: '100% Cotton Organic chuẩn GOTS',
      origin: 'Việt Nam xuất khẩu Nhật',
      safetyStandard: 'Không formaldehyde, thuốc nhuộm an toàn loại 1',
      size: '0-3 tháng, 3-6 tháng, 6-9 tháng, 9-12 tháng',
    },
    price: 245000,
    originalPrice: 350000,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 80,
    rating: 4.9,
    numReviews: 48,
    isFeatured: true,
    isFlashSale: true,
  },
  {
    name: 'Bộ Quần Áo Dài Tay Thu Đông Họa Tiết Thỏ Đáng Yêu Cho Bé Gái',
    slug: 'bo-quan-ao-dai-tay-thu-dong-hoa-tiet-tho-cho-be-gai',
    brand: 'Petit Baby',
    categorySlug: 'quan-ao-thoi-trang-be',
    ageGroup: '1-3y',
    gender: 'girl',
    description: 'Bộ quần áo thun nỉ bông mịn giữ ấm hoàn hảo cho bé gái trong những ngày giao mùa. Họa tiết thỏ in nước an toàn không bong tróc sau nhiều lần giặt. Cạp chun bản rộng mềm mại không gây lằn bụng bé.',
    specifications: {
      material: 'Nỉ bông hữu cơ pha sợi tơ tằm',
      origin: 'Hàn Quốc nhập khẩu',
      safetyStandard: 'Chứng nhận an toàn da liễu cho trẻ',
      size: 'Size 80 (8-10kg), Size 90 (10-12kg), Size 100 (12-14kg)',
    },
    price: 189000,
    originalPrice: 260000,
    images: [
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 65,
    rating: 4.8,
    numReviews: 32,
    isFeatured: true,
    isFlashSale: false,
  },
  {
    name: 'Áo Khoác Gió Kháng Nước Lót Lông Siêu Nhẹ Cho Bé Trai & Gái',
    slug: 'ao-khoac-gio-khang-nuoc-lot-long-sieu-nhe',
    brand: 'Kids Pro',
    categorySlug: 'quan-ao-thoi-trang-be',
    ageGroup: '3-6y',
    gender: 'unisex',
    description: 'Áo khoác 2 lớp cản gió và sương sớm vượt trội. Mặt ngoài xử lý công nghệ trượt nước, mặt trong lót lớp nỉ cừu nhân tạo giữ ấm mà vẫn siêu nhẹ, giúp bé thỏa sức vận động chạy nhảy ngoài trời.',
    specifications: {
      material: 'Vải Polyester trượt nước cao cấp + Lót nỉ nhung',
      origin: 'Việt Nam gia công xuất khẩu',
      safetyStandard: 'Khóa kéo YKK êm ái có bọc đầu bảo vệ cằm',
      size: '100cm, 110cm, 120cm',
    },
    price: 295000,
    originalPrice: 420000,
    images: [
      'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 45,
    rating: 4.9,
    numReviews: 29,
    isFeatured: false,
    isFlashSale: true,
  },
  {
    name: 'Mũ Len Tai Gấu Kèm Khăn Ống Giữ Ấm Sành Điệu Cho Bé',
    slug: 'mu-len-tai-gau-kem-khan-ong-cho-be',
    brand: 'GrowKid Soft',
    categorySlug: 'quan-ao-thoi-trang-be',
    ageGroup: '1-3y',
    gender: 'unisex',
    description: 'Set mũ len tai gấu dễ thương đan tay tỉ mỉ từ sợi len sữa không ngứa, không rụng lông. Đi kèm khăn quàng cổ dạng ống ôm khít cổ bé, bảo vệ hệ hô hấp trong mùa đông giá lạnh.',
    specifications: {
      material: 'Sợi len sữa organic dệt kim',
      origin: 'Việt Nam',
      safetyStandard: 'Không kích ứng, mềm mượt như mây',
      size: 'Freesize cho bé từ 6 tháng đến 3 tuổi',
    },
    price: 99000,
    originalPrice: 150000,
    images: [
      'https://images.unsplash.com/photo-1543332164-6e82f355badc?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 120,
    rating: 4.7,
    numReviews: 54,
    isFeatured: false,
    isFlashSale: false,
  },
  {
    name: 'Bảng Gỗ Bận Rộn Busy Board Montessori Phát Triển Kỹ Năng Vận Động Tinh',
    slug: 'bang-go-ban-ron-busy-board-montessori',
    brand: 'Montessori Kids',
    categorySlug: 'do-choi-thong-minh-van-dong',
    ageGroup: '1-3y',
    gender: 'unisex',
    description: 'Bộ đồ chơi giáo dục sớm mô phỏng các hoạt động thực tế: khóa cửa, công tắc đèn, bánh răng xoay, buộc dây giày, đồng hồ xoay kim. Giúp trẻ rèn luyện đôi bàn tay khéo léo, khả năng tập trung và tính tự lập cao.',
    specifications: {
      material: 'Gỗ tự nhiên nguyên khối phủ sơn nước không chì',
      origin: 'Việt Nam sản xuất chuẩn CE xuất khẩu Châu Âu',
      safetyStandard: 'Góc cạnh bo tròn 100%, không dằm xước',
      size: '40cm x 30cm x 5cm (Trọng lượng 1.8kg)',
    },
    price: 385000,
    originalPrice: 550000,
    images: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 35,
    rating: 5.0,
    numReviews: 67,
    isFeatured: true,
    isFlashSale: false,
  },
  {
    name: 'Bộ Xếp Hình Lego Gạch Lớn Sáng Tạo 88 Chi Tiết An Toàn Cho Bé',
    slug: 'bo-xep-hinh-lego-gach-lon-sang-tao-88-chi-tiet',
    brand: 'PlayKids Master',
    categorySlug: 'do-choi-thong-minh-van-dong',
    ageGroup: '1-3y',
    gender: 'unisex',
    description: 'Bộ gạch xây dựng cỡ lớn được thiết kế vừa vặn với lòng bàn tay nhỏ của bé, chống nuốt hóc tuyệt đối. Tương thích với các khối gạch Lego Duplo, kích thích trí tưởng tượng không gian và tư duy hình khối logic.',
    specifications: {
      material: 'Nhựa nguyên sinh ABS cao cấp',
      origin: 'Hàng chính hãng tiêu chuẩn quốc tế',
      safetyStandard: 'Không chứa BPA, đạt chuẩn an toàn đồ chơi QCVN 3:2019',
      size: 'Hộp đựng tiện lợi dung tích 15L kèm nắp lắp ráp',
    },
    price: 280000,
    originalPrice: 390000,
    images: [
      'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 50,
    rating: 4.9,
    numReviews: 41,
    isFeatured: true,
    isFlashSale: true,
  },
  {
    name: 'Xe Thăng Bằng Khung Nhôm Siêu Nhẹ 1.9kg Tập Đi Cho Bé Từ 2 Đến 6 Tuổi',
    slug: 'xe-thang-bang-khung-nhom-sieu-nhe-chong-lat',
    brand: 'Ander Balance',
    categorySlug: 'do-choi-thong-minh-van-dong',
    ageGroup: '3-6y',
    gender: 'unisex',
    description: 'Xe thăng bằng giúp trẻ rèn luyện phản xạ giữ thăng bằng, tự tin đạp chân vận động thể chất ngoài trời. Khung nhôm anode hóa chống rỉ sét, yên xe êm ái bọc đệm có thể điều chỉnh độ cao linh hoạt theo chiều cao của bé.',
    specifications: {
      material: 'Hợp kim nhôm hàng không siêu bền nhẹ',
      origin: 'Chính hãng bảo hành 2 năm',
      safetyStandard: 'Lốp cao su đặc chống đinh, vòng bi bạc đạn siêu êm',
      size: 'Bánh 12 inch, tải trọng tối đa 35kg',
    },
    price: 690000,
    originalPrice: 950000,
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 25,
    rating: 4.9,
    numReviews: 38,
    isFeatured: true,
    isFlashSale: false,
  },
  {
    name: 'Bình Sữa Cổ Rộng Kháng Đầy Hơi Silicone Siêu Mềm Comotomo 250ml',
    slug: 'binh-sua-co-rong-silicone-sieu-mem-comotomo-250ml',
    brand: 'Comotomo USA',
    categorySlug: 'sua-thuc-pham-an-dam',
    ageGroup: '0-12m',
    gender: 'unisex',
    description: 'Bình sữa quốc dân mô phỏng bầu ngực mẹ tự nhiên, chất liệu 100% silicone y tế mềm mại đàn hồi cao giúp bé dễ dàng chuyển từ ti mẹ sang ti bình mà không bị bỡ ngỡ. Hệ thống 2 van thông khí chống sặc và đầy hơi hiệu quả.',
    specifications: {
      material: 'Silicone y tế cao cấp chịu nhiệt 180°C',
      origin: 'Hàn Quốc / Chính hãng phân phối',
      safetyStandard: 'BPA Free, PVC Free, Phthalate Free',
      size: 'Dung tích 250ml kèm núm ti 2 tia (3-6 tháng)',
    },
    price: 365000,
    originalPrice: 420000,
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 110,
    rating: 4.9,
    numReviews: 128,
    isFeatured: true,
    isFlashSale: true,
  },
  {
    name: 'Tã Quần Merries First Premium Siêu Thoáng Khí Nhật Bản (Size M/L/XL)',
    slug: 'ta-quan-merries-first-premium-sieu-thoang-khi-nhat-ban',
    brand: 'Merries KAO',
    categorySlug: 'ta-bim-cham-soc-ve-sinh',
    ageGroup: '0-12m',
    gender: 'unisex',
    description: 'Dòng tã cao cấp nhất của tập đoàn KAO Nhật Bản, bề mặt lượn sóng 3D êm ái gấp 2 lần, bổ sung chiết xuất dầu argan tinh khiết dưỡng ẩm cho da bé. Vách chống tràn thông minh co giãn ôm trọn vòng đùi mà không để lại vết hằn.',
    specifications: {
      material: 'Bông tự nhiên không dệt kết hợp hạt SAP siêu ngậm nước',
      origin: 'Nhập khẩu 100% nguyên đai từ Nhật Bản',
      safetyStandard: 'Chứng nhận không gây kích ứng da trẻ sơ sinh',
      size: 'Size M (6-11kg: 58 miếng), Size L (9-14kg: 44 miếng), XL (12-22kg: 38 miếng)',
    },
    price: 345000,
    originalPrice: 410000,
    images: [
      'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 200,
    rating: 5.0,
    numReviews: 185,
    isFeatured: true,
    isFlashSale: true,
  },
  {
    name: 'Xe Đẩy Gấp Gọn Du Lịch Siêu Nhẹ 4.5kg 2 Chiều 3 Tư Thế Aprica Air',
    slug: 'xe-day-gap-gon-du-lich-sieu-nhe-2-chieu-aprica-air',
    brand: 'Aprica Japan',
    categorySlug: 'xe-day-diu-noi-cui-em-be',
    ageGroup: '0-12m',
    gender: 'unisex',
    description: 'Xe đẩy trẻ em cao cấp với trọng lượng siêu nhẹ 4.5kg, gấp gọn bằng một tay trong 1 giây để xách lên máy bay hoặc đặt vừa cốp xe máy. Tay đẩy 2 chiều giúp mẹ vừa đẩy vừa giao tiếp với bé. Đệm lưng thoáng khí tản nhiệt tốt.',
    specifications: {
      material: 'Khung nhôm siêu nhẹ + Vải dù chống tia cực tím UPF 50+',
      origin: 'Nhật Bản / Bảo hành 36 tháng',
      safetyStandard: 'Đai an toàn 5 điểm chuẩn quốc tế, phanh chân một chạm',
      size: 'Ngả 3 tư thế từ 110° đến 175° (phù hợp từ sơ sinh đến 4 tuổi)',
    },
    price: 1850000,
    originalPrice: 2450000,
    images: [
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=700&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=700&auto=format&fit=crop&q=80',
    ],
    countInStock: 18,
    rating: 5.0,
    numReviews: 36,
    isFeatured: true,
    isFlashSale: false,
  },
];

module.exports = { categoriesData, productsData };
